packaging_format = 2

id = "affine"
name = "AFFiNE"
description.fr = "Espace de travail open-source (docs + tableau blanc)."
description.en = "Open-source workspace (docs + whiteboard)."
version = "0.2.0~ynh1"

maintainers = ["EpicTGuy <github@users.noreply.github.com>"]

[upstream]
license = "MIT"
code = "https://github.com/toeverything/AFFiNE"

architectures = ["amd64", "arm64"]
multi_instance = true
services = ["affine"]

[install]
  [install.domain]
  type = "domain"
  ask.fr = "Choisissez un domaine pour AFFiNE"
  ask.en = "Choose a domain for AFFiNE"

  [install.path]
  type = "path"
  default = "/affine"

  [install.init_main_permission]
  type = "group"
  default = "visitors"

[resources]
  [resources.system_user]
  name = "__APP__"

  [resources.ports]
    [resources.ports.main]
    default = 4090

  [resources.databases]
    [resources.databases.main]
    type = "postgresql"

  [resources.data]
  paths = ["data", "config"]

  [resources.sources.main]
  # ← épingle un tag AFFiNE ci-dessous et mets le sha256 correspondant
  url = "https://github.com/toeverything/AFFiNE/archive/refs/tags/v0.15.0.tar.gz"
  sha256 = "31ef9aa794d76eab58ba2e0b2694d295bcb2c39dca169d770c50084e00907d98"
  in_subdir = true