packaging_format = 2

id = "affine"
name = "AFFiNE"
description.fr = "Espace de travail open-source (docs + whiteboard), paquet YunoHost (brouillon de test)."
description.en = "Open-source workspace (docs + whiteboard), YunoHost package (smoke test)."
version = "0.0.1~ynh1"

maintainers = ["EpicTGuy <github@users.noreply.github.com>"]

[upstream]
license = "MIT"
code = "https://github.com/toeverything/AFFiNE"

[install]
  [install.domain]
  type = "domain"
  ask.fr = "Choisissez un domaine pour AFFiNE"
  ask.en = "Choose a domain for AFFiNE"

  [install.path]
  type = "path"
  default = "/affine"
  ask.fr = "Choisissez un chemin"
  ask.en = "Choose a path"

  [install.init_main_permission]
  type = "group"
  default = "visitors" # public pour le test
  ask.fr = "Qui peut accéder à l'application ? (visitors ou all_users)"
  ask.en = "Who can access the app? (visitors or all_users)"

[resources]
  [resources.system_user]
  name = "__APP__"

  [resources.ports]
    [resources.ports.main]
    default = 4090

  [resources.data]
  paths = ["data", "config"]

  # On laissera les sources vides pour le smoke test ; on générera un mini serveur côté install