#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2
id = "affine"
name = "AFFiNE"
description.en = "A next-generation collaborative knowledge base and whiteboard for flexible project management."
description.fr = "Une base de connaissances collaborative de nouvelle génération et un tableau blanc pour une gestion de projet flexible."
version = "0.10.0~ynh1"
maintainers = ["Clément <maintainer@hom-e.fr>"]

[upstream]
license = "MIT"
website = "https://affine.pro"
demo = "https://demo.affine.pro"
admindoc = "https://docs.affine.pro/admin"
userdoc = "https://docs.affine.pro/user"
code = "https://github.com/toeverything/AFFiNE"
cpe = "cpe:2.3:a:toeverything:affine"
fund = "https://opencollective.com/affine"

[integration]
yunohost = ">= 4.3.0"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = true
sso = true
disk = "3G"
ram.build = "2G"
ram.runtime = "512M"

[install]
  [install.domain]
  type = "domain"
  
  [install.path]
  type = "path"
  default = "/affine"
  
  [install.is_public]
  type = "boolean"
  default = false
  ask.en = "Make the application public?"
  ask.fr = "Rendre l'application publique ?"
  help.en = "If enabled, the application will be accessible without authentication."
  help.fr = "Si activé, l'application sera accessible sans authentification."
  
  [install.init_main_permission]
  type = "group"
  default = "visitors"
  
  [install.admin]
  type = "user"
  
  [install.password]
  type = "password"
  help.en = "Enter the administrator password for AFFiNE."
  help.fr = "Entrez le mot de passe administrateur pour AFFiNE."

[resources]
  [resources.sources]
    [resources.sources.main]
    url = "https://github.com/toeverything/AFFiNE/releases/download/v0.10.0/affine-v0.10.0-linux-x64.tar.gz"
    sha256 = "a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456"
    autoupdate.strategy = "latest_github_release"
    
  [resources.system_user]
  
  [resources.install_dir]
  
  [resources.data_dir]
  
  [resources.permissions]
  main.url = "/"
  
  [resources.ports]
  main.port = 3000
  
  [resources.apt]
  packages = ["nodejs", "npm", "build-essential", "python3", "python3-pip"]
  
  [resources.database]
  type = "postgresql"
  