#!/bin/bash
set -eu
source /usr/share/yunohost/helpers
ynh_abort_if_errors

app="$YNH_APP_INSTANCE_NAME"
install_dir="/var/www/$app"

# Sauvegarde fichiers de conf et données uniquement
ynh_backup_if_checksum --file="$install_dir/.env"
ynh_backup --src_path="$install_dir/data"
ynh_backup --src_path="$install_dir/config"

ynh_print_info "Backup terminé pour $app."