#!/bin/bash
set -eu
source /usr/share/yunohost/helpers
ynh_abort_if_errors

app="$YNH_APP_INSTANCE_NAME"

# Stop + disable service
ynh_systemd_action --service_name="$app" --action=stop --log_path="systemd" || true
ynh_remove_systemd_config --service="$app"

# Remove NGINX
ynh_remove_nginx_config

# Remove Node runtime
ynh_nodejs_remove --package "$app"

# Remove user
ynh_system_user_delete --username="$app"

# Note: /var/www/$app est conservé par défaut pour sécurité
# Décommente la ligne suivante si tu veux supprimer les données :
# ynh_secure_remove --file="/var/www/$app"